# Pre-commit hooks configuration for Web Notes API
# Ensures code quality and consistency before commits

repos:

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3.13
        files: ^(backend|tests)/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        files: ^(backend|tests)/.*\.py$
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        files: ^(backend|tests)/.*\.py$
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        files: ^backend/.*\.py$
        additional_dependencies:
          - types-requests
          - fastapi
          - uvicorn
        args: [--ignore-missing-imports]

  # JavaScript/HTML formatting and linting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^chrome-extension/.*\.(js|html|json)$
        additional_dependencies:
          - prettier@3.2.5

  # ESLint for JavaScript linting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: ^chrome-extension/.*\.js$
        additional_dependencies:
          - eslint@8.57.1
          - eslint-config-prettier@9.1.0

# Configuration for specific tools
exclude: |
  (?x)^(
    \.venv/.*|
    \.git/.*|
    __pycache__/.*|
    .*\.pyc|
    requirements/requirements\.lock|
    node_modules/.*|
    .*\.min\.(js|css)
  )$
