"""Initial migration with all tables

Revision ID: c4976df58a70
Revises:
Create Date: 2025-09-26 12:36:48.177106

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c4976df58a70"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("provider_type", sa.String(length=50), nullable=False),
        sa.Column("api_endpoint", sa.String(length=255), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("max_tokens", sa.Integer(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_providers_id"), "llm_providers", ["id"], unique=False)
    op.create_index(
        op.f("ix_llm_providers_name"), "llm_providers", ["name"], unique=True
    )
    op.create_table(
        "sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("user_context", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sites_domain"), "sites", ["domain"], unique=True)
    op.create_index(op.f("ix_sites_id"), "sites", ["id"], unique=False)
    op.create_table(
        "pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("page_summary", sa.Text(), nullable=True),
        sa.Column("user_context", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pages_id"), "pages", ["id"], unique=False)
    op.create_index(op.f("ix_pages_site_id"), "pages", ["site_id"], unique=False)
    op.create_index(op.f("ix_pages_url"), "pages", ["url"], unique=False)
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("position_x", sa.Integer(), nullable=True),
        sa.Column("position_y", sa.Integer(), nullable=True),
        sa.Column(
            "anchor_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("server_link_id", sa.String(length=100), nullable=True),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notes_id"), "notes", ["id"], unique=False)
    op.create_index(op.f("ix_notes_page_id"), "notes", ["page_id"], unique=False)
    op.create_index(
        op.f("ix_notes_server_link_id"), "notes", ["server_link_id"], unique=False
    )
    op.create_table(
        "page_sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("section_type", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("selector", sa.String(length=500), nullable=True),
        sa.Column("xpath", sa.String(length=500), nullable=True),
        sa.Column("position_in_page", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_page_sections_id"), "page_sections", ["id"], unique=False)
    op.create_index(
        op.f("ix_page_sections_page_id"), "page_sections", ["page_id"], unique=False
    )
    op.create_table(
        "note_artifacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artifact_type", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("prompt_used", sa.Text(), nullable=True),
        sa.Column(
            "generation_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("note_id", sa.Integer(), nullable=False),
        sa.Column("llm_provider_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["llm_provider_id"], ["llm_providers.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["note_id"], ["notes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_note_artifacts_id"), "note_artifacts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_note_artifacts_llm_provider_id"),
        "note_artifacts",
        ["llm_provider_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_note_artifacts_note_id"), "note_artifacts", ["note_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_note_artifacts_note_id"), table_name="note_artifacts")
    op.drop_index(
        op.f("ix_note_artifacts_llm_provider_id"), table_name="note_artifacts"
    )
    op.drop_index(op.f("ix_note_artifacts_id"), table_name="note_artifacts")
    op.drop_table("note_artifacts")
    op.drop_index(op.f("ix_page_sections_page_id"), table_name="page_sections")
    op.drop_index(op.f("ix_page_sections_id"), table_name="page_sections")
    op.drop_table("page_sections")
    op.drop_index(op.f("ix_notes_server_link_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_page_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_id"), table_name="notes")
    op.drop_table("notes")
    op.drop_index(op.f("ix_pages_url"), table_name="pages")
    op.drop_index(op.f("ix_pages_site_id"), table_name="pages")
    op.drop_index(op.f("ix_pages_id"), table_name="pages")
    op.drop_table("pages")
    op.drop_index(op.f("ix_sites_id"), table_name="sites")
    op.drop_index(op.f("ix_sites_domain"), table_name="sites")
    op.drop_table("sites")
    op.drop_index(op.f("ix_llm_providers_name"), table_name="llm_providers")
    op.drop_index(op.f("ix_llm_providers_id"), table_name="llm_providers")
    op.drop_table("llm_providers")
    # ### end Alembic commands ###
